server:
  port: 8080

spring:
  application:
    name: binance-trading-app
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/binance_trading}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

# 바이낸스 API 설정
binance:
  api:
    base-url: https://api.binance.com
    stream-url: wss://stream.binance.com:9443/ws/
  
# 로깅 설정
logging:
  level:
    com.binancetrader: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# CORS 설정
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:5000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"